version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: app@app.com
      PGADMIN_DEFAULT_PASSWORD: app 
    depends_on:
      - postgres

  flyway:
    container_name: flyway
    image: flyway/flyway
    volumes:
      - ./database/migrations:/flyway/sql
      - ./database/scripts/:/flyway/scripts
    entrypoint: ["sh", "-c", "/flyway/scripts/wait-for-it.sh postgres:5432 -t 60 -- /flyway/flyway -url=jdbc:postgresql://postgres:5432/app -user=app -password=app -locations=filesystem:/flyway/sql migrate"]
    depends_on:
      - postgres